version: '3.4'
services:
  web-server:
    image: harbor.ittim-online.com/avis_release/web_server:latest
    restart: always
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
      - INFLUX_DOMAIN=${INFLUX_DOMAIN}
      - CLIENT_HTTP_PORT=${CLIENT_HTTP_PORT}
      - RESELLER_DOMAIN=${RESELLER_DOMAIN} 
    ports:
      - "80:80"
      - "443:443"
      - "${CLIENT_HTTP_PORT}:${CLIENT_HTTP_PORT}"
    volumes:
      - ./data/web:/opt/data
      
  reseller-web:
    image: harbor.ittim-online.com/avis_release/reseller_web_server:latest
    restart: always
    environment:
      - RESELLER_DOMAIN=${RESELLER_DOMAIN}      

  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=avis
    volumes:
      - ./data/db:/var/lib/mysql

  management-api:
    image: harbor.ittim-online.com/avis_release/management_api:latest
    restart: always
    volumes:
      - ./data/license:/opt/license
    environment:
      - TZ=${TIMEZONE}
      - MARIADB_PASS=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=root
      - MARIADB_IP=mariadb
      - JWT_KEY=${JWT_KEY}
      - MINIO_IP=minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_SERVER=http://influxdb2:8086
      - DOMAIN=${DOMAIN}
      - CLIENT_HTTP_PORT=${CLIENT_HTTP_PORT}
      - TMDB_KEY=${TMDB_KEY}
 
  worker-api:
    image: harbor.ittim-online.com/avis_release/worker_api:latest
    restart: always
    ports:
      - "8001:8001"
      - "8003:8003"
    environment:
      - TZ=${TIMEZONE}
      - MARIADB_PASS=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=root
      - MARIADB_IP=mariadb
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - DOMAIN=${DOMAIN}
      - SERVER_IP=${SERVER_IP}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_SERVER=http://influxdb2:8086
    volumes:
      - ./data/worker_api:/opt/data
      - ./data/license:/opt/license

  certificate-authority:
    image: harbor.ittim-online.com/avis_release/certificate_authority:latest
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - MARIADB_PASS=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=root
      - MARIADB_IP=mariadb
      - ORGANIZATION=${ORGANIZATION}
      - COUNTRY_CODE=${COUNTRY_CODE}
      - PROVINCE=${PROVINCE}
      - CITY=${CITY}
      - ADDRESS=${ADDRESS}
      - POSTAL_CODE=${POSTAL_CODE}    
    volumes:
      - ./data/CA:/opt/data

  reseller-api:
    image: harbor.ittim-online.com/avis_release/reseller_api:latest
    restart: always
    volumes:
      - ./data/license:/opt/license
    environment:
      - TZ=${TIMEZONE}
      - MARIADB_PASS=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=root
      - MARIADB_IP=mariadb
      - JWT_KEY_RESELLER=${JWT_KEY_RESELLER}
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - DOMAIN=${DOMAIN}
      - CLIENT_HTTP_PORT=${CLIENT_HTTP_PORT}

  Minio:
    image: minio/minio:latest
    restart: always
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - ./data/minio:/data

  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./data/redis/:/data/

  influxdb2:
    image: influxdb:2.7
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: 'setup'
      DOCKER_INFLUXDB_INIT_USERNAME: 'admin'
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: 'avis'
      DOCKER_INFLUXDB_INIT_BUCKET: 'init'
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb2/:/var/lib/influxdb2
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=/phpmyadmin
